"""add security operations and attendance controls

Revision ID: 48463e284ed5
Revises: c9f45a12d803
Create Date: 2026-08-23 19:48:07.568333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48463e284ed5'
down_revision = 'c9f45a12d803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if not sa.inspect(bind).has_table('schedule_write_locks'):
        op.create_table('schedule_write_locks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('touched_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    existing_lock = bind.execute(sa.text("SELECT id FROM schedule_write_locks WHERE id = 1")).first()
    if not existing_lock:
        op.execute(sa.text("INSERT INTO schedule_write_locks (id, touched_at) VALUES (1, CURRENT_TIMESTAMP)"))
    op.create_table('minimum_wage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('hourly_wage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('minimum_wage_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_minimum_wage_rates_effective_date'), ['effective_date'], unique=True)
    op.execute(
        sa.text(
            "INSERT INTO minimum_wage_rates "
            "(effective_date, hourly_wage, created_by, created_at) "
            "VALUES ('2026-01-01', 196, NULL, CURRENT_TIMESTAMP)"
        )
    )

    op.create_table('staff_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_staff_availability_time_order'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_availability', schema=None) as batch_op:
        batch_op.create_index('ix_staff_availability_staff_date', ['staff_id', 'availability_date'], unique=False)

    op.create_table('attendance_reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('calculated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payable_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_reconciliations_shift_id'), ['shift_id'], unique=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes_json', sa.Text(), nullable=True))

    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_drill_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_drill_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_drill_message', sa.String(length=500), nullable=True))

    with op.batch_alter_table('attendance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offline_threshold_minutes', sa.Integer(), nullable=False, server_default='15'))

    with op.batch_alter_table('attendance_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_secret_encrypted', sa.Text(), nullable=True))

    op.create_table('attendance_review_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=False),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['attendance_events.id']),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_review_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_review_history_event_id'), ['event_id'], unique=False)

    op.create_table('shift_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('undone_by', sa.Integer(), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id']),
    sa.ForeignKeyConstraint(['undone_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id'))
    op.add_column('shifts', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shifts_import_batch_id'), 'shifts', ['import_batch_id'], unique=False)
    if bind.dialect.name != 'sqlite':
        op.create_foreign_key('fk_shifts_import_batch_id', 'shifts', 'shift_import_batches', ['import_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint('fk_shifts_import_batch_id', 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_import_batch_id'), table_name='shifts')
    op.drop_column('shifts', 'import_batch_id')
    op.drop_table('shift_import_batches')

    with op.batch_alter_table('attendance_review_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_review_history_event_id'))
    op.drop_table('attendance_review_history')

    with op.batch_alter_table('attendance_devices', schema=None) as batch_op:
        batch_op.drop_column('pending_secret_encrypted')

    with op.batch_alter_table('attendance_policies', schema=None) as batch_op:
        batch_op.drop_column('offline_threshold_minutes')

    with op.batch_alter_table('backup_runs', schema=None) as batch_op:
        batch_op.drop_column('last_drill_message')
        batch_op.drop_column('last_drill_status')
        batch_op.drop_column('last_drill_at')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('changes_json')

    with op.batch_alter_table('attendance_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_reconciliations_shift_id'))

    op.drop_table('attendance_reconciliations')
    with op.batch_alter_table('staff_availability', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_availability_staff_date')

    op.drop_table('staff_availability')
    with op.batch_alter_table('minimum_wage_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_minimum_wage_rates_effective_date'))

    op.drop_table('minimum_wage_rates')
    op.drop_table('schedule_write_locks')
    # ### end Alembic commands ###
