"""add phase 3 leave swap and audit workflows

Revision ID: 79d4488d8faa
Revises: 486c51e89d9e
Create Date: 2026-08-10 17:30:02.473785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d4488d8faa'
down_revision = '486c51e89d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('safe_summary', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_staff_id'), ['staff_id'], unique=False)

    op.create_table('swap_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requester_shift_id', sa.Integer(), nullable=False),
    sa.Column('target_staff_id', sa.Integer(), nullable=False),
    sa.Column('target_shift_id', sa.Integer(), nullable=True),
    sa.Column('peer_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='swappeerstatus', native_enum=False), nullable=False),
    sa.Column('admin_status', sa.Enum('NOT_READY', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='swapadminstatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('peer_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['staff_profiles.id'], ),
    sa.ForeignKeyConstraint(['requester_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['target_staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swap_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swap_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swap_requests_requester_shift_id'), ['requester_shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swap_requests_target_shift_id'), ['target_shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swap_requests_target_staff_id'), ['target_staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swap_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swap_requests_target_staff_id'))
        batch_op.drop_index(batch_op.f('ix_swap_requests_target_shift_id'))
        batch_op.drop_index(batch_op.f('ix_swap_requests_requester_shift_id'))
        batch_op.drop_index(batch_op.f('ix_swap_requests_requester_id'))

    op.drop_table('swap_requests')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_staff_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_shift_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
