"""add actionable notification center

Revision ID: aa16f55dd9f5
Revises: c4e208981061
Create Date: 2026-08-11 22:02:28.425892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa16f55dd9f5'
down_revision = 'c4e208981061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_key', sa.String(length=180), nullable=False),
    sa.Column('recipient_role', sa.Enum('ADMIN', 'STUDENT', name='role', native_enum=False), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title_zh', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('message_zh', sa.String(length=500), nullable=False),
    sa.Column('message_en', sa.String(length=500), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'COMPLETED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(recipient_role IS NOT NULL AND recipient_user_id IS NULL) OR (recipient_role IS NULL AND recipient_user_id IS NOT NULL)', name='ck_notification_single_recipient'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_key'), ['notification_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_role'), ['recipient_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_role'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_key'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
