"""add nationalities and foreign student scheduling policy

Revision ID: acce6927c641
Revises: aece1306b930
Create Date: 2026-08-12 21:19:33.764099

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = 'acce6927c641'
down_revision = 'aece1306b930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('is_taiwan', sa.Boolean(), nullable=False),
    sa.Column('weekly_limit_exempt', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    op.create_table('scheduling_exception_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name='ck_scheduling_exception_date_order'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduling_exception_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduling_exception_periods_ends_on'), ['ends_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduling_exception_periods_starts_on'), ['starts_on'], unique=False)

    op.create_table('scheduling_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foreign_weekly_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_hour_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    bind = op.get_bind()
    now = datetime.now(timezone.utc)
    bind.execute(
        sa.text("UPDATE staff_profiles SET nationality = '台灣' WHERE lower(nationality) IN ('taiwan', 'roc') OR nationality IN ('臺灣', '中華民國')")
    )
    country_rows = [
        {
            "code": "TW",
            "name": "台灣",
            "name_en": "Taiwan",
            "is_taiwan": True,
            "weekly_limit_exempt": False,
            "display_order": 10,
            "is_active": True,
            "created_at": now,
            "updated_at": now,
        }
    ]
    existing_names = list(
        bind.execute(
            sa.text("SELECT DISTINCT nationality FROM staff_profiles WHERE nationality IS NOT NULL AND nationality <> '' AND nationality <> '台灣' ORDER BY nationality")
        ).scalars()
    )
    for index, name in enumerate(existing_names, start=1):
        country_rows.append(
            {
                "code": f"NAT{index:03d}",
                "name": name,
                "name_en": name,
                "is_taiwan": False,
                "weekly_limit_exempt": False,
                "display_order": 100 + index,
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            }
        )
    countries_table = sa.table(
        "countries",
        sa.column("code", sa.String), sa.column("name", sa.String), sa.column("name_en", sa.String),
        sa.column("is_taiwan", sa.Boolean), sa.column("weekly_limit_exempt", sa.Boolean),
        sa.column("display_order", sa.Integer), sa.column("is_active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)), sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(countries_table, country_rows)
    policy_table = sa.table(
        "scheduling_policies",
        sa.column("id", sa.Integer), sa.column("foreign_weekly_limit_enabled", sa.Boolean),
        sa.column("weekly_hour_limit", sa.Numeric), sa.column("updated_by", sa.Integer),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(policy_table, [{"id": 1, "foreign_weekly_limit_enabled": True, "weekly_hour_limit": 20, "updated_by": None, "updated_at": now}])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduling_policies')
    with op.batch_alter_table('scheduling_exception_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduling_exception_periods_starts_on'))
        batch_op.drop_index(batch_op.f('ix_scheduling_exception_periods_ends_on'))

    op.drop_table('scheduling_exception_periods')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###
