"""add security audit request metadata

Revision ID: aece1306b930
Revises: aa16f55dd9f5
Create Date: 2026-08-12 10:54:35.355100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aece1306b930'
down_revision = 'aa16f55dd9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('http_method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('route', sa.String(length=255), nullable=True))
        batch_op.alter_column('actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_route'), ['route'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 舊 schema 不允許匿名操作者；回退前移除無法表示的失敗登入事件。
    op.execute(sa.text("DELETE FROM audit_logs WHERE actor_user_id IS NULL"))
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_route'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ip_address'))
        batch_op.alter_column('actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('route')
        batch_op.drop_column('http_method')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
