"""add secure staff document workflow

Revision ID: b4852085ec6b
Revises: 79d4488d8faa
Create Date: 2026-08-10 18:44:00.871446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4852085ec6b'
down_revision = '79d4488d8faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('RESIDENCE_PERMIT', 'WORK_PERMIT', name='documenttype', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(length=120), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'NEEDS_REVIEW', 'CONFIRMED', 'REPLACED', 'FAILED', 'DELETED', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('privacy_notice_version', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_status', sa.String(length=30), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extracted_data_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('staff_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_documents_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_documents_status'), ['status'], unique=False)

    op.create_table('document_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.String(length=100), nullable=True),
    sa.Column('residence_expiry', sa.Date(), nullable=True),
    sa.Column('work_permit_number', sa.String(length=100), nullable=True),
    sa.Column('work_permit_start', sa.Date(), nullable=True),
    sa.Column('work_permit_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['staff_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_drafts')
    with op.batch_alter_table('staff_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_documents_status'))
        batch_op.drop_index(batch_op.f('ix_staff_documents_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_staff_documents_document_type'))

    op.drop_table('staff_documents')
    # ### end Alembic commands ###
